##### BEGIN modeco/Dockerfile/image-header #####
FROM vcwebio/conteco.image.wrapper AS base
##### END modeco/Dockerfile/image-header #####

##### BEGIN modeco/Dockerfile/conteco #####
COPY ./modeco/ /modeco/
RUN rm -rf /conteco/repo
COPY ./ /conteco/repo/
##### END modeco/Dockerfile/conteco #####

##### BEGIN image/Dockerfile/build-instructions #####
##### END image/Dockerfile/build-instructions #####

##### BEGIN modeco/Dockerfile/env-labels-footer #####
ENV CONTECO_REALM="vcwebio" \
    CONTECO_ECOSYSTEM="conteco" \
    CONTECO_TYPE="package" \
    CONTECO_NAME="registry" \
    CONTECO_TAG="v1.0.0" \
    CONTECO_BASE="image.wrapper" \
    CONTECO_BUILD="modeco"
LABEL io.vcweb.schema-version="1.0" \
      io.vcweb.realm="vcwebio" \
      io.vcweb.ecosystem="conteco" \
      io.vcweb.type="package" \
      io.vcweb.name="registry" \
      io.vcweb.tag="v1.0.0" \
      io.vcweb.base="image.wrapper" \
      io.vcweb.build="modeco" \
      io.vcweb.label="package.registry - ModEco" \
      io.vcweb.description="The regsitry module package." \
      io.vcweb.docker.cmd.help="docker run vcwebio/conteco.package.registry --help"
##### END modeco/Dockerfile/env-labels-footer #####
