#!/usr/bin/env bash

export CONTECO_LABEL="package.traefik - ModEco"
export CONTECO_DESCRIPTION="The traefik module package."

export CONTECO_TYPE="package"
export CONTECO_NAME="traefik"
export CONTECO_TAG="v2.1"


export CONTECO_BASE="image.wrapper"
export CONTECO_BUILD="modeco"
